### ISSUE TITLE
All commands give "ModuleNotFoundError: No module named 'pkg_resources'"

### ISSUE THREAD

**Issue by iainelder** [Rishang/install-release#200]
This happens on Ubuntu 24.04.1. LTS.

```
$ pipx install install-release
  installed package install-release 0.4.4, installed using Python 3.12.3
  These apps are now globally available
    - install-release
    - ir
done! ✨ 🌟 ✨

$ ir
Traceback (most recent call last):
  File "/home/isme/.local/bin/ir", line 5, in <module>
    from InstallRelease.cli import app
  File "/home/isme/.local/pipx/venvs/install-release/lib/python3.12/site-packages/InstallRelease/cli.py", line 9, in <module>
    from InstallRelease.utils import pprint, logger
  File "/home/isme/.local/pipx/venvs/install-release/lib/python3.12/site-packages/InstallRelease/utils.py", line 16, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

It's a pity, because install-release is the easiest way to install stuff from GitHub right now :-)

**Comment by Rishang** [comment]
try: `pip install -U setuptools`

**Comment by iainelder** [comment]
Thanks, @Rishang . The missing piece was `setuptools`. After I added that, the `ir` command gave the normal output.

```
$ pipx inject install-release setuptools
  injected package setuptools into venv install-release
done! ✨ 🌟 ✨
$ install-release^C
$ ir
Usage: ir [OPTIONS] COMMAND [ARGS]...
Try 'ir --help' for help.
╭─ Error ────────────────────────────────────────────────────────────────────────────────────╮
│ Missing command.                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────╯
```

It turns out that Python 3.12 no longer preinstalls `setuptools` in a new virtual environment.

[Python 3.12 What's New](https://docs.python.org/3/whatsnew/3.12.html):

> [gh-95299](https://github.com/python/cpython/issues/95299): Do not pre-install `setuptools` in virtual environments created with [`venv`](https://docs.python.org/3/library/venv.html#module-venv). This means that `distutils`, `setuptools`, `pkg_resources`, and `easy_install` will no longer available by default; to access these run `pip install setuptools` in the [activated](https://docs.python.org/3/library/venv.html#venv-explanation) virtual environment.
