### ISSUE TITLE
Change in 0.2.9 breaks PATH and makes installed programs unusable

### ISSUE THREAD

**Issue by jrobison-sb** [Rishang/install-release#33]
**Describe the bug**
Something changed in 0.2.9 which causes installed programs to be installed outside of the `$PATH` described in the documentation. My guess is it was [this change](https://github.com/Rishang/install-release/commit/16020778b809f3f78f2cf2a84ba04c5e2a084bdf#diff-9250a895699fd61c2e67e7b78a0494c715c18c34d4977c4b1e68ab85b8f6b567L7-R7). This is easily reproducible on-demand, see below for an example.

**Expected behavior**
First, here is the expected behavior based on how the documentation tells me to install this and set a PATH, and in 0.2.8 it works just fine:

```
$ docker run -it --rm ubuntu:22.04

# All remaining steps happen inside the container on Ubuntu

root@55f1b60c0706:/# apt-get update > /dev/null && apt-get install -y libmagic1 python3-pip > /dev/null

root@55f1b60c0706:/# pip3 install install-release==0.2.8 > /dev/null

root@55f1b60c0706:/# export PATH=$HOME/.release-bin:$PATH

root@55f1b60c0706:/# install-release get -y https://github.com/minamijoyo/hcledit
 INFO     Downloaded: 'hcledit_0.2.6_linux_amd64.tar.gz' at /tmp/dn_hcledit_ebdemovo                 utils.py:187
 INFO     install /tmp/dn_hcledit_ebdemovo/hcledit /root/.release-bin/hcledit                         core.py:144
 INFO     Installed: hcledit                                                                          core.py:151

root@55f1b60c0706:/# which hcledit
/root/.release-bin/hcledit
```

**To Reproduce**

And here is how you can see that it is broken in 0.2.9:
```
$ docker run -it --rm ubuntu:22.04

# All remaining steps happen inside the container on Ubuntu

root@9cf15c5ebcc0:/# apt-get update > /dev/null && apt-get install -y libmagic1 python3-pip > /dev/null

root@9cf15c5ebcc0:/# pip3 install install-release==0.2.9 > /dev/null

root@9cf15c5ebcc0:/# export PATH=$HOME/.release-bin:$PATH

root@9cf15c5ebcc0:/# install-release get -y https://github.com/minamijoyo/hcledit
 INFO     Downloaded: 'hcledit_0.2.6_linux_amd64.tar.gz' at /tmp/dn_hcledit_cwzsintt                 utils.py:187
 INFO     install /tmp/dn_hcledit_cwzsintt/hcledit /root/bin/hcledit                                  core.py:144
 INFO     Installed: hcledit                                                                          core.py:151

root@9cf15c5ebcc0:/# which hcledit

# There is no output for `which hcledit`, so it's clearly not in the path. This confirms the broken behavior.

# I can fix it by adding `$HOME/bin` to my PATH, but I don't see that anywhere in the documentation.

root@9cf15c5ebcc0:/# export PATH=$HOME/bin:$PATH

root@9cf15c5ebcc0:/# which hcledit
/root/bin/hcledit
```

**Additional context**

Note that when I try using 0.3.0, I get the same behavior seen in the 0.2.9 example above. 

Users who are brand new to this tool could easily be unblocked if `export PATH=$HOME/bin:$PATH` was added to the docs, so they knew that they needed this PATH for installed programs.

But existing users who have existing scripts will need to fix their scripts, either by adding the PATH above or by pinning version 0.2.8, neither of which is optimal for them. It would be best for them if the tool preserved the same workflow that they were already expecting from 0.2.8.

**Comment by Rishang** [comment]
Hey there thanks for raising this issue,

yes I have update [default path](https://github.com/Rishang/install-release/commit/16020778b809f3f78f2cf2a84ba04c5e2a084bdf#diff-9250a895699fd61c2e67e7b78a0494c715c18c34d4977c4b1e68ab85b8f6b567L7-R7) of installing releases to you will require to update paths of `$PATH` as follows for version after `0.2.9`

```bash
export PATH=$HOME/bin:$PATH
```

**Comment by Rishang** [comment]
Also i have update it in docs as well

**Comment by Rishang** [comment]
Also in order to re-install tools of new -> `~/bin` path you can use:

```bash
install-release upgrade -F
``` 

which will forcefully re-install all previous tools

**Comment by Rishang** [comment]
I hope your issue is fixed, you can re-open it if its not been solved yet, closing for now
